language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  app: boiling-plains-75461
  api_key:
    secure: gy7qevAj7MqhgXtD8+cQJ1UInSu3ewd/X/dR9iXgAOKMzCYbpdzPVcO8F17LmBFKJbAgrqA1aftMMPm7LWjTOUuH8dt9n6RemehZ4q5+ViJL09Gad70WEu1F8u04b2e8FDiffe/sYKAsdSg7AFQJ0VPzrh2rGdoFlxZrC/fFsrQZ7y/T1zMb7zRWMyQ24C0DIifjpjV8z8hSR9x0RAlmqfEx58d4ngpPLouQRJ4xy+rPWxla+hnX4pg4UECW6VB7PMCeNsk1B4v2anP3b/7izAZuwAX6bRykdOOcwsyxQC6BoyB2z+5pig/4BKHltdTKqlKVMQbDMjKxQuYO5n49JHmQ1YqbyU7GOrDN2CHKPVlHZQcaTmStQgHtkb4V2uXThPWKpGJDGtUhd02F28p2TStZg24gSa8aM3NE0gJWPfgKrPNkrZobK6n2dPT0wJSRC/vXCj1WQvmNjzBpP1wuNC86cQ446Q8YQkEZh0PwHxpDPp6+Xg035wvuR792G6XpZ6aeSMz6mgXAjXcYEKil8Xc9HS3dlgtsUPJIl8hwZGAt0h5hPbw4A2dtvlJ6pswACRnl9fIgdq9LFadKt0lHekoZCEQVqWTpvHuXY7sNc6dtsl1XSx1+0X1QKwMEowJKEPqUoq6XavDpGZ+Nn/z0LidaD0LghwVzkdNy2JutX5k=
